/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


		import java.util.regex.Pattern;
		import java.util.regex.Matcher;
	
public interface HDFqlConstants {
  public final static String VERSION = HDFqlJNI.VERSION_get();
  public final static int BUFFER_SIZE = HDFqlJNI.BUFFER_SIZE_get();
  public final static int YES = HDFqlJNI.YES_get();
  public final static int NO = HDFqlJNI.NO_get();
  public final static int ENABLED = HDFqlJNI.ENABLED_get();
  public final static int DISABLED = HDFqlJNI.DISABLED_get();
  public final static int DEFAULT = HDFqlJNI.DEFAULT_get();
  public final static int UNDEFINED = HDFqlJNI.UNDEFINED_get();
  public final static int GLOBAL = HDFqlJNI.GLOBAL_get();
  public final static int LOCAL = HDFqlJNI.LOCAL_get();
  public final static int TRACKED = HDFqlJNI.TRACKED_get();
  public final static int INDEXED = HDFqlJNI.INDEXED_get();
  public final static int DIRECTORY = HDFqlJNI.DIRECTORY_get();
  public final static int FILE = HDFqlJNI.FILE_get();
  public final static int GROUP = HDFqlJNI.GROUP_get();
  public final static int DATASET = HDFqlJNI.DATASET_get();
  public final static int ATTRIBUTE = HDFqlJNI.ATTRIBUTE_get();
  public final static int SOFT_LINK = HDFqlJNI.SOFT_LINK_get();
  public final static int HARD_LINK = HDFqlJNI.HARD_LINK_get();
  public final static int EXTERNAL_LINK = HDFqlJNI.EXTERNAL_LINK_get();
  public final static int CONTIGUOUS = HDFqlJNI.CONTIGUOUS_get();
  public final static int COMPACT = HDFqlJNI.COMPACT_get();
  public final static int CHUNKED = HDFqlJNI.CHUNKED_get();
  public final static int TINYINT = HDFqlJNI.TINYINT_get();
  public final static int UNSIGNED_TINYINT = HDFqlJNI.UNSIGNED_TINYINT_get();
  public final static int SMALLINT = HDFqlJNI.SMALLINT_get();
  public final static int UNSIGNED_SMALLINT = HDFqlJNI.UNSIGNED_SMALLINT_get();
  public final static int INT = HDFqlJNI.INT_get();
  public final static int UNSIGNED_INT = HDFqlJNI.UNSIGNED_INT_get();
  public final static int BIGINT = HDFqlJNI.BIGINT_get();
  public final static int UNSIGNED_BIGINT = HDFqlJNI.UNSIGNED_BIGINT_get();
  public final static int FLOAT = HDFqlJNI.FLOAT_get();
  public final static int DOUBLE = HDFqlJNI.DOUBLE_get();
  public final static int CHAR = HDFqlJNI.CHAR_get();
  public final static int VARTINYINT = HDFqlJNI.VARTINYINT_get();
  public final static int UNSIGNED_VARTINYINT = HDFqlJNI.UNSIGNED_VARTINYINT_get();
  public final static int VARSMALLINT = HDFqlJNI.VARSMALLINT_get();
  public final static int UNSIGNED_VARSMALLINT = HDFqlJNI.UNSIGNED_VARSMALLINT_get();
  public final static int VARINT = HDFqlJNI.VARINT_get();
  public final static int UNSIGNED_VARINT = HDFqlJNI.UNSIGNED_VARINT_get();
  public final static int VARBIGINT = HDFqlJNI.VARBIGINT_get();
  public final static int UNSIGNED_VARBIGINT = HDFqlJNI.UNSIGNED_VARBIGINT_get();
  public final static int VARFLOAT = HDFqlJNI.VARFLOAT_get();
  public final static int VARDOUBLE = HDFqlJNI.VARDOUBLE_get();
  public final static int VARCHAR = HDFqlJNI.VARCHAR_get();
  public final static int OPAQUE = HDFqlJNI.OPAQUE_get();
  public final static int NATIVE_ENDIAN = HDFqlJNI.NATIVE_ENDIAN_get();
  public final static int LITTLE_ENDIAN = HDFqlJNI.LITTLE_ENDIAN_get();
  public final static int BIG_ENDIAN = HDFqlJNI.BIG_ENDIAN_get();
  public final static int ASCII = HDFqlJNI.ASCII_get();
  public final static int UTF8 = HDFqlJNI.UTF8_get();
  public final static int SUCCESS = HDFqlJNI.SUCCESS_get();
  public final static int ERROR_PARSE = HDFqlJNI.ERROR_PARSE_get();
  public final static int ERROR_NOT_FOUND = HDFqlJNI.ERROR_NOT_FOUND_get();
  public final static int ERROR_NO_ACCESS = HDFqlJNI.ERROR_NO_ACCESS_get();
  public final static int ERROR_ALREADY_EXISTS = HDFqlJNI.ERROR_ALREADY_EXISTS_get();
  public final static int ERROR_EMPTY = HDFqlJNI.ERROR_EMPTY_get();
  public final static int ERROR_FULL = HDFqlJNI.ERROR_FULL_get();
  public final static int ERROR_BEFORE_FIRST = HDFqlJNI.ERROR_BEFORE_FIRST_get();
  public final static int ERROR_AFTER_LAST = HDFqlJNI.ERROR_AFTER_LAST_get();
  public final static int ERROR_NO_ADDRESS = HDFqlJNI.ERROR_NO_ADDRESS_get();
  public final static int ERROR_NOT_REGISTERED = HDFqlJNI.ERROR_NOT_REGISTERED_get();
  public final static int ERROR_OUTSIDE_LIMIT = HDFqlJNI.ERROR_OUTSIDE_LIMIT_get();
  public final static int ERROR_UNKNOWN = HDFqlJNI.ERROR_UNKNOWN_get();
}
