!this is a test code to check the working of module "modulehdf5r.f90"
! this program calls the hdf5 module file which intern calls the hdf5 program and reads the data files generated by mesh creation.

program usehdf5 ! this is a test program
use hdfwrite ! uses the module to generate file
implicit none 
call hdf5wrt ! calls the subroutine for mesh generation
end program usehdf5
